# Generated by Django 4.1.9 on 2023-12-02 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_email', models.CharField(max_length=75, verbose_name='Who Added')),
                ('fn', models.TextField()),
                ('sha1', models.CharField(blank=True, max_length=40, null=True)),
                ('size', models.IntegerField()),
                ('date_added', models.DateField()),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('file', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='file_versions.filemodel')),
            ],
        ),
    ]
