# Generated by Django 4.1.9 on 2023-12-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_versions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileversion',
            options={'verbose_name': 'File Version', 'verbose_name_plural': 'File Versions'},
        ),
    ]
